s/gdb50start/startdebug50 s/gdb50stop/stopdebug50

diff --git a/bin/debug50 b/bin/debug50
--- a/bin/debug50
+++ b/bin/debug50
@@ -36,13 +36,13 @@ PID=$$
 
 # SIGUSR1 signals to begin the shim
 SHIM="/home/ubuntu/.c9/bin/c9gdbshim.js"
-trap "node $SHIM $*; $C9 gdb50stop $PID; echo; exit 0" SIGUSR1
+trap "node $SHIM $*; $C9 stopdebug50 $PID; echo; exit 0" SIGUSR1
 
 # give PID to proxy for monitoring
-ERR="$($C9 gdb50start $PID)"
+ERR="$($C9 startdebug50 $PID)"
 
 # c9 exec doesn't return non-zero on error!
-if [ "$ERR" = "Could not execute gdb50start" ]; then
+if [ "$ERR" = "Could not execute startdebug50" ]; then
     echo "Unable to start!"
     exit 1
 fi
